name: build + deploy

on:
  push:
    branches: ["new2022"]
  pull_request:
    branches: ["new2022"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write 

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17.2.0
        uses: actions/setup-node@v3
        with:
          node-version: 17.2.0
          cache: "npm"
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - run: npm run build --if-present
      - run: npm run test --if-present
      - name: set remote
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: git remote set-url origin "https://$GITHUB_TOKEN@github.com/frc-emotion/website.git"
      - run: npm run actions-deploy
