name: build + deploy

on:
  push:
    branches: ["new2022"]
  pull_request:
    branches: ["new2022"]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: fregante/setup-git-user@v1
      - name: Use Node.js 17.2.0
        uses: actions/setup-node@v3
        with:
          node-version: 17.2.0
          cache: "npm"
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
      - run: npm run build --if-present
      - run: npm run test --if-present
      - run: git remote set-url origin https://github.com/frc-emotion/website.git
      - run: npm run actions-deploy
