name: npm deploy to pages

on:
  push:
    branches: [ "new2022" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 17.2.0
      uses: actions/setup-node@v3
      with:
        node-version: 17.2.0
        cache: 'npm'
    - run: npm i
    - run: npm run predeploy
    - run: npm run actions-deploy
