name: build

on:
  pull_request:
    branches: ["new2022"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 17.2.0
        uses: actions/setup-node@v3
        with:
          node-version: 17.2.0
          cache: "npm"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - run: npm run build --if-present
      - run: npm run test --if-present
